### ISSUE TITLE
Select "Current Location"

### ISSUE THREAD

**Issue by jianjye** [almassapargali/LocationPicker#13]
Hi @almassapargali , thanks for the great plugin! 

I am wondering if it is possible to add the "Select" button for "Current Location" annotation? Currently when tapping on the blue circle of current location, it shows the annotation but not the Select button. 

Any way I can enable it or add it in? 

Thanks!

**Comment by almassapargali** [comment]
It's standard iOS pin. I'll check if I can help you when I get to my Mac.

**Comment by jianjye** [comment]
@almassapargali Thanks for the quick reply. Hopefully it's doable.

**Comment by almassapargali** [comment]
Hello, it looks like if you can replicate standard iOS current location pin [here](https://github.com/almassapargali/LocationPicker/blob/master/LocationPicker/LocationPickerViewController.swift#L338), you could return it instead of `nil` when `annotation is MKUserLocation` with added `rightCalloutAccessoryView`.

I'm not sure if this feature is needed by many users, and don't want to complicate unless many requests comes for this feature. For now, I'd suggest you to fork, and make mentioned changes.

**Comment by jianjye** [comment]
@almassapargali Right now, the current location blue circle does not respond to long press to enable selection like the rest of the map. So if I want to enable selecting "current location" as my desired output, I would need to perform my own detection and setting locationPicker.location before going into locationPicker. 

It would certainly be great if you would consider this use case. 

Thanks!

**Comment by almassapargali** [comment]
Made long press gesture work on current location blue dot too. Sorry for delay!
